// <auto-generated />
using System;
using AstromusicApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AstromusicApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("AstromusicApi.models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .HasColumnType("longtext");

                    b.Property<string>("FullName")
                        .HasColumnType("longtext");

                    b.Property<int>("ZodiacSignId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ZodiacSignId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("AstromusicApi.models.ZodiacSign", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<int>("EndDay")
                        .HasColumnType("int");

                    b.Property<int>("EndMonth")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<string>("SongArtist")
                        .HasColumnType("longtext");

                    b.Property<string>("SongLink")
                        .HasColumnType("longtext");

                    b.Property<int>("StartDay")
                        .HasColumnType("int");

                    b.Property<int>("StartMonth")
                        .HasColumnType("int");

                    b.Property<string>("ThemeSong")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("ZodiacSigns");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Intensa e cheia de atitude, dona da própria verdade e energia incansável. Quem segura? Só Beyoncé mesmo, miga!",
                            EndDay = 20,
                            EndMonth = 4,
                            ImageUrl = "",
                            Name = "Áries",
                            SongArtist = "Beyoncé",
                            SongLink = "https://open.spotify.com/track/0bZ8K5yx2SUQTE0n7bJoRi",
                            StartDay = 21,
                            StartMonth = 3,
                            ThemeSong = "Don't Hurt Yourself"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Apreciadora dos prazeres da vida, fiel e autêntica. Traz aquele glamour safadérrimo e a vibe luxuosa da Amy.",
                            EndDay = 20,
                            EndMonth = 5,
                            ImageUrl = "",
                            Name = "Touro",
                            SongArtist = "Amy Winehouse",
                            SongLink = "https://open.spotify.com/track/3CK2hZfPmW8A0nHqQxCajR",
                            StartDay = 21,
                            StartMonth = 4,
                            ThemeSong = "F*** Me Pumps"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Mil facetas, 1000 opiniões por segundo. Rápida no papo, adora um caos, rainha do reboliço igual Nicki.",
                            EndDay = 20,
                            EndMonth = 6,
                            ImageUrl = "",
                            Name = "Gêmeos",
                            SongArtist = "Nicki Minaj",
                            SongLink = "https://open.spotify.com/track/4F7A0DXBrmUAkp32uenhQk",
                            StartDay = 21,
                            StartMonth = 5,
                            ThemeSong = "Roman's Revenge"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Emo delicinha, sentimental, entrega o coração de bandeja. Uma música doce e sincera da Kehlani é o mood.",
                            EndDay = 21,
                            EndMonth = 7,
                            ImageUrl = "",
                            Name = "Câncer",
                            SongArtist = "Kehlani",
                            SongLink = "https://open.spotify.com/track/5V5PTEzOeF8J4vH05m0Qel",
                            StartDay = 21,
                            StartMonth = 6,
                            ThemeSong = "Honey"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Rainha do palco, centro das atenções. Entrega o *twerk*, entrega o poder, igual Megan feat. Queen B!",
                            EndDay = 22,
                            EndMonth = 8,
                            ImageUrl = "",
                            Name = "Leão",
                            SongArtist = "Megan Thee Stallion feat. Beyoncé",
                            SongLink = "https://open.spotify.com/track/3Remixlink",
                            StartDay = 22,
                            StartMonth = 7,
                            ThemeSong = "Savage Remix"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Perfeccionista, discreta, organizada, mas super envolvente, com um R&B viciante tipo Summer Walker.",
                            EndDay = 22,
                            EndMonth = 9,
                            ImageUrl = "",
                            Name = "Virgem",
                            SongArtist = "Summer Walker",
                            SongLink = "https://open.spotify.com/track/5hQSMw0tYhfbWf0WgZqkDQ",
                            StartDay = 23,
                            StartMonth = 8,
                            ThemeSong = "Body"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Estilosa, charmosa, busca equilíbrio até no batom. Música deep da Rihanna, pra dar close certo.",
                            EndDay = 22,
                            EndMonth = 10,
                            ImageUrl = "",
                            Name = "Libra",
                            SongArtist = "Rihanna feat. SZA",
                            SongLink = "https://open.spotify.com/track/0ikz6tENMONtK6qGkOrU3c",
                            StartDay = 23,
                            StartMonth = 9,
                            ThemeSong = "Consideration"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Intensa, misteriosa, provocante. O dark da Lana é seu habitat natural.",
                            EndDay = 21,
                            EndMonth = 11,
                            ImageUrl = "",
                            Name = "Escorpião",
                            SongArtist = "Lana Del Rey",
                            SongLink = "https://open.spotify.com/track/6jG2YzhxptolDzLHTGLt7S",
                            StartDay = 23,
                            StartMonth = 10,
                            ThemeSong = "Gods & Monsters"
                        },
                        new
                        {
                            Id = 9,
                            Description = "Livre, criativa, irreverente. Melanie entrega a vibe lúdica, diferente e nada óbvia.",
                            EndDay = 21,
                            EndMonth = 12,
                            ImageUrl = "",
                            Name = "Sagitário",
                            SongArtist = "Melanie Martinez",
                            SongLink = "https://open.spotify.com/track/1gVgkEC0AHTy9y5xrwtO3A",
                            StartDay = 22,
                            StartMonth = 11,
                            ThemeSong = "Strawberry Shortcake"
                        },
                        new
                        {
                            Id = 10,
                            Description = "Ambiciosa, poderosa, não dá ponto sem nó. A Beyoncé de “Upgrade U” é sua mentora.",
                            EndDay = 20,
                            EndMonth = 1,
                            ImageUrl = "",
                            Name = "Capricórnio",
                            SongArtist = "Beyoncé feat. Jay-Z",
                            SongLink = "https://open.spotify.com/track/6O8A4hZ9VgoWvNEmkbD9g0",
                            StartDay = 22,
                            StartMonth = 12,
                            ThemeSong = "Upgrade U"
                        },
                        new
                        {
                            Id = 11,
                            Description = "Visionária, única, sempre com um papo profundo. Jhené Aiko com B.S., pra quem pensa fora da caixa.",
                            EndDay = 19,
                            EndMonth = 2,
                            ImageUrl = "",
                            Name = "Aquário",
                            SongArtist = "Jhené Aiko feat. H.E.R.",
                            SongLink = "https://open.spotify.com/track/2Q4pFzK4qvU3hZLhM4nY5z",
                            StartDay = 21,
                            StartMonth = 1,
                            ThemeSong = "B.S."
                        },
                        new
                        {
                            Id = 12,
                            Description = "Sensível, artista, vive no mundo dos sonhos. Lana entrega a atmosfera onírica perfeita.",
                            EndDay = 20,
                            EndMonth = 3,
                            ImageUrl = "",
                            Name = "Peixes",
                            SongArtist = "Lana Del Rey",
                            SongLink = "https://open.spotify.com/track/1vZCtb8pAz9VLtMoA5pBWi",
                            StartDay = 20,
                            StartMonth = 2,
                            ThemeSong = "The Grants"
                        });
                });

            modelBuilder.Entity("AstromusicApi.models.User", b =>
                {
                    b.HasOne("AstromusicApi.models.ZodiacSign", "ZodiacSign")
                        .WithMany("Users")
                        .HasForeignKey("ZodiacSignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ZodiacSign");
                });

            modelBuilder.Entity("AstromusicApi.models.ZodiacSign", b =>
                {
                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
